### ISSUE TITLE
Can we approach a solution to [81247276] by adding a route to /users?

### ISSUE THREAD

**Issue by jasenmh** [scalableinternetservicesarchive/LaPlaya#13]
If a user wants to get to another users profile, one way would be to use the /users route to show all users and allow the current user to click on the user she's interested in.

Another option would be a search function.

**Comment by jhenkens** [comment]
b5f2c68d92d2b4ad71391ab6657c2360e288049a

started it there

**Comment by jhenkens** [comment]
Note the repetition in it between it and galleries. Specifically the for loop rendering all the objects. We could definitely factor that out.

**Comment by jhenkens** [comment]
I think a search function would be cool - I've never done that. Specifically drop-down-only search might be neat for something like this.

**Comment by jhenkens** [comment]
Also, the `/users` namespace in the routes is usually best to keep to just registration/session creation, editing and management.
