### ISSUE TITLE
new rails asset gems break the CloudFormation builds

### ISSUE THREAD

**Issue by kjorg50** [scalableinternetservicesarchive/LaPlaya#20]
I _think_ that's what is causing these kind of errors:

```
rake aborted!
Bundler::VersionConflict: Could not find gem 'rails-assets-desandro--get-size (< 2, >= 1) ruby', which is required by gem 'rails-assets-isotope (>= 0) ruby', in any of the sources.
/home/ec2-user/app/config/boot.rb:4:in `<top (required)>'
/home/ec2-user/app/config/application.rb:1:in `<top (required)>'
/home/ec2-user/app/Rakefile:4:in `<top (required)>'
LoadError: cannot load such file -- bundler/setup
/home/ec2-user/app/config/boot.rb:4:in `<top (required)>'
/home/ec2-user/app/config/application.rb:1:in `<top (required)>'
/home/ec2-user/app/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
expr $loop - 1)
expr $loop - 1
```

Create a stack and look in `/var/log/cloud-init-output.log`

**Comment by jhenkens** [comment]
Can we use Gemfile.lock on AWS? I'd bet $3.50 that having versions specified in a Gemfile.lock, and just calling bundle install, would fix this.

**Comment by kjorg50** [comment]
Bryce previously said that we should not use Gemfile.lock on AWS, we should talk to him later

**Comment by kjorg50** [comment]
Tried adding the Gemfile.lock, but it seems to have the same issue. Take a look at the `deploy-test` branch. Or connect here `ssh -i LaPlaya.pem ec2-user@54.68.50.224` and look at the logs

**Comment by jhenkens** [comment]
I don't know why it didn't like just reading from the Gemfile as dependencies or Gemfile.lock, perhaps @bboe has some insight, but I added the gem as an explicit requirement in the Gemfile ( as well as moved `factory-girl` and `faker`. 

I'd like to note that bundler thought it was building just fine,

```
Installing sdoc 0.4.1
Installing therubyracer 0.12.1
Installing uglifier 2.5.3
Installing will_paginate 3.0.7
Your bundle is complete!
Gems in the groups test and development were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

but it was simply ignoring one of the dependencies from our Gemfile.lock, which would then cause the rake tasks to fail

```
rake aborted!
Bundler::VersionConflict: Could not find gem 'rails-assets-desandro--get-size (< 2, >= 1) ruby', which is required by gem 'rails-assets-isotope (>= 0) ruby', in any of the sources.
/home/ec2-user/app/config/boot.rb:4:in `<top (required)>'
/home/ec2-user/app/config/application.rb:1:in `<top (required)>'
```

When I added it as a static requirement rather than just through dependencies, it started building again, but seemed to fail after seeding (or I just don't know how to start deployments properly).

```
== 20141115213215 AddDeletedToComments: migrating =============================
-- add_column(:comments, :deleted, :boolean, {:default=>false})
   -> 0.0247s
== 20141115213215 AddDeletedToComments: migrated (0.0248s) ====================

if [ $loop -eq 0 ]; then
  error_exit 'Failed to execute database migration'
fi
# Run the app specific ec2 initialization
if [ -f .ec2_initialize ]; then
    sudo -u ec2-user bash -l .ec2_initialize     || error_exit 'Failed to run .ec2_initialize'
fi

Broadcast message from root@ip-172-31-2-199
    (unknown) at 22:46 ...

The system is going down for power off NOW!
Connection to 54.69.219.133 closed by remote host.
Connection to 54.69.219.133 closed.
```

**Comment by jhenkens** [comment]
See 7915cc016d7a58e4be2e33edc957e7141cafd7d4

**Comment by bboe** [comment]
The seeding issue may be due to my comments here: https://github.com/scalableinternetservices/LaPlaya/commit/d8e65170d1cd5659a0b67dbd3f2727e7a79eda62

I don't know about the Gemfile dependency issue.

**Comment by kjorg50** [comment]
~~The export statements for our env variables work from the .bashrc file, but the rake command does not. In the logs we end up with `/home/ec2-user/.bashrc: line 14: rake: command not found`. See 466b3863f2b13d9b0ad150973f2f0a4bd38a8044~~

EDIT: please disregard this comment

**Comment by kjorg50** [comment]
This time the seed creation and the bundle install worked, but for some reason it failed after starting the serve. I'm not sure when it goes into the CREATE_FAILED state...

```
# Start up WEBrick (or whatever server is installed)
sudo -u ec2-user bash -lc "rails server -d" || error_exit 'Failed to start rails server'
=> Booting WEBrick
=> Rails 4.1.8 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
# All is well so signal success
/opt/aws/bin/cfn-signal -e 0 --stack LaPlaya-rake --resource AppServer   --region us-west-2
ValidationError: Stack LaPlaya-rake is in CREATE_FAILED state and cannot be signaled
Nov 21 07:00:22 cloud-init[1300]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Nov 21 07:00:22 cloud-init[1300]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Nov 21 07:00:22 cloud-init[1300]: util.py[WARNING]: Running scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.6/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
```

**Comment by bboe** [comment]
This output seems to indicate that it took _too long_ to initialize the instance. If the EC2 instance doesn't finish within 5 minutes, it is considered failed. Did everything appear to work even though it was in the failed state?

**Comment by kjorg50** [comment]
Thanks for the quick response! I think it takes about 5 minutes to create all the seed data, and everything appeared to work, so that is certainly possible. I know we could go into the instance and manually run `rake db:seed`, but are there any alternative ways we could automate it?

**Comment by bboe** [comment]
You can change the timeout time in your own cloud config. I don't want to change the timeout time for everyone as 5 minutes is a reasonable timeout.

Look for `PT5M` and change to something like `PT15M`.

**Comment by jhenkens** [comment]
I think we should just remove seeding from the deployment, or have a ‘mini-seed’ that we can use just to test new builds that is auto deployed, and a full seed we can run via ssh+rake.

–––––––––––––––––
Johan Henkens
johan@henkens.com

**Comment by kjorg50** [comment]
thanks @bboe that worked! @jhenkens I'll work on that
