### ISSUE TITLE
Portfolio items mouseover doesn't load correctly on EC2

### ISSUE THREAD

**Issue by kjorg50** [scalableinternetservicesarchive/LaPlaya#22]
![css_fail](https://cloud.githubusercontent.com/assets/3325973/5152183/d1c7948e-71a0-11e4-997b-cf95af408043.png)

When deploying on EC2, the solid portfolio items don't load quite right. The links that should appear on mouseover just appear below the images. Maybe this has something to do with how the assets get loaded?

**Comment by jhenkens** [comment]
I have no idea how to deploy, every time I try it build fine but then deletes itself after starting the web server.

I pushed what I think is a fix in PR #19, but idk.

–––––––––––––––––
Johan Henkens
johan@henkens.com

**Comment by kjorg50** [comment]
When creating a stack, on the "Options" menu, click the "Advanced" section and choose "No" for rollback on failure

**Comment by jhenkens** [comment]
Fixed.
