### ISSUE TITLE
no pagination?

### ISSUE THREAD

**Issue by kjorg50** [scalableinternetservicesarchive/LaPlaya#26]
![no_pagination](https://cloud.githubusercontent.com/assets/3325973/5195033/eeaf3fde-74ca-11e4-85fc-9d4a62c28ea0.png)

Not sure why this is happening, but the pagination doesn't show up when deployed on EC2.

**Comment by kjorg50** [comment]
I also experience this problem on localhost

**Comment by charlottehill** [comment]
Yeah it looks like the line that gives you links to the other pages got deleted. I just added it back!

**Comment by jhenkens** [comment]
Ah I see it. Yep. Thanks guys.
