### ISSUE TITLE
Error when destroying a project with a tag

### ISSUE THREAD

**Issue by kjorg50** [scalableinternetservicesarchive/LaPlaya#30]
![screenshot 2014-12-02 19 33 55](https://cloud.githubusercontent.com/assets/3325973/5275506/47155b10-7a5a-11e4-9421-2da08d670506.png)

**Comment by kjorg50** [comment]
Also, if you then edit the project, remove the tag, and try deleting the project, there is an `NaN` error being generated from the tag_cloud module in app/helpers/projects_helper.rb

**Comment by jhenkens** [comment]
Same error happens for project_likes, so it was pretty easy to nail down. Has-Many-Through tables need to have a primary key. I had no idea.
