### ISSUE TITLE
Not authorized error (cancancan)

### ISSUE THREAD

**Issue by kjorg50** [scalableinternetservicesarchive/LaPlaya#9]
![cancan_error](https://cloud.githubusercontent.com/assets/3325973/4989396/0f99238a-692d-11e4-8d4e-89e4bff2ce0a.png)

I clicked 'edit' on a project that I didn't create and this came up.

Possible solutions (off the top of my head):
- create a redirect and show a flash message
- no redirect and just a flash message if not authorized
- only show edit/destroy buttons if the project belongs to the currently logged in user. Can we use _cancancan_ in views in this way?

**Comment by jhenkens** [comment]
https://github.com/CanCanCommunity/cancancan#2-check-abilities--authorization

Just hide the link. We don't really need to have a pretty unauthorized page.

**Comment by jasenmh** [comment]
But won't this be adding the logic to the views that we didn't want to @jhenkens ?

**Comment by jhenkens** [comment]
I honestly don't know of the best way to do conditional view logic like this. The only other way I know is to do a helper method like this

https://github.com/scalableinternetservices/LaPlaya/blob/99ae7935b234420125b165968310a134ddca8af7/app/helpers/comments_helper.rb

And just have it like <%= project_links %> and then have the helper put the links together.

But the cancancan documentation has it being done in the view itself, and I tried googling alternatives and came up dry.

**Comment by jhenkens** [comment]
Uhh, I don't know how or what I did with amutz.

**Comment by jasenmh** [comment]
Additionally, there's already a can? block around the edit action. As I understand it, in ability.rb in models, the initialize() method says if you aren't logged in, you get read in Projects, Galleries and Comments and nothing else because user == nil when you aren't logged in.

**Comment by jasenmh** [comment]
Well, let's just let him have this one then. =)

**Comment by jasenmh** [comment]
Nevermind, I see the problem.

**Comment by jasenmh** [comment]
![image](https://cloud.githubusercontent.com/assets/2660276/5004284/500be98c-69cf-11e4-8ae6-677c06777d0f.png)

No more edit button.

**Comment by jasenmh** [comment]
Fixed.
